/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PorodnicaAmbulanceHome {
    }
}
declare global {
    interface HTMLPorodnicaAmbulanceHomeElement extends Components.PorodnicaAmbulanceHome, HTMLStencilElement {
    }
    var HTMLPorodnicaAmbulanceHomeElement: {
        prototype: HTMLPorodnicaAmbulanceHomeElement;
        new (): HTMLPorodnicaAmbulanceHomeElement;
    };
    interface HTMLElementTagNameMap {
        "porodnica-ambulance-home": HTMLPorodnicaAmbulanceHomeElement;
    }
}
declare namespace LocalJSX {
    interface PorodnicaAmbulanceHome {
    }
    interface IntrinsicElements {
        "porodnica-ambulance-home": PorodnicaAmbulanceHome;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "porodnica-ambulance-home": LocalJSX.PorodnicaAmbulanceHome & JSXBase.HTMLAttributes<HTMLPorodnicaAmbulanceHomeElement>;
        }
    }
}
